### ISSUE TITLE
Problem with PathOGiST conda build 0.3.2

### ISSUE THREAD

**Issue by realseanla** [WGS-TB/PathOGiST#30]
I installed PathOGiST via conda (version 0.3.2) using the following commands:
```bash
conda create --name pathogist
source activate pathogist
conda install pathogist
```
After the successful installation, I tried to make a new blank configuration file for the subcommand `PATHOGIST run` using the following command:
```bash
PATHOGIST run test.config -n
```
I received the following error:
```bash
Traceback (most recent call last):
  File "/home/laseanl/Software/miniconda3/envs/pathogist/bin/PATHOGIST", line 611, in run_all
    shutil.copyfile(src_path,param.config)
  File "/home/laseanl/Software/miniconda3/envs/pathogist/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/laseanl/Software/miniconda3/envs/pathogist/bin/pathogi
st/resources/blank_config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laseanl/Software/miniconda3/envs/pathogist/bin/PATHOGIST", line 862, in <module>
    main()
  File "/home/laseanl/Software/miniconda3/envs/pathogist/bin/PATHOGIST", line 851, in main
    run_all(param, MAJOR_VERSION, MINOR_VERSION)
  File "/home/laseanl/Software/miniconda3/envs/pathogist/bin/PATHOGIST", line 614, in run_all
    .format(major, minor), param.config)
  File "/home/laseanl/Software/miniconda3/envs/pathogist/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/laseanl/Software/miniconda3/envs/pathogist/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/laseanl/Software/miniconda3/envs/pathogist/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/laseanl/Software/miniconda3/envs/pathogist/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/laseanl/Software/miniconda3/envs/pathogist/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/laseanl/Software/miniconda3/envs/pathogist/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/laseanl/Software/miniconda3/envs/pathogist/lib/python3.7/urllib/request.py", line 649, in http_error_de
fault
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by matnguyen** [comment]
https://github.com/WGS-TB/PathOGiST/commit/b08a795fbfdfd21c60b7b0c5bf9d2dce5e46c3ad resolved this issue.

The new version of Bioconda is now available.
